server.port=8080

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

logging.level.org.zalando.logbook=TRACE

logging.level.ru.yandex.practicum.filmorate=DEBUG

logging.level.org.springframework.web=INFO

logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss

logbook.format.style=json
logbook.obfuscate.headers=Authorization
logbook.obfuscate.parameters=password
logbook.write.category=org.zalando.logbook.Logbook

spring.jackson.serialization.indent_output=true

spring.main.banner-mode=off
